[#install-container]
= Container install (podman/docker)

include::snippit_container.adoc[]

include::snippit_container_registries.adoc[]

If you prefer to use docker-compose, then follow the <<install-compose,docker-compose installation instructions>>.

The standard container setup just needs **port 1337** forwarded for web traffic, and a volume **to store the configuration file**. Note that OliveTin containers expect the config to be in `/config/` inside the container, but it doesn't really matter where this directory is mounted from on the host. This documention uses the convention of `/etc/OliveTin` on the host, but `/dockerStuff/OliveTin/` or similar would be fine.

[source, shell]
.Create the container (but don't start it yet)
....
user@host: mkdir /etc/OliveTin/
user@host: # ie: Your config file is /etc/OliveTin/config.yaml on the host machine. We'll create this in the post-installation step.
user@host: docker pull jamesread/olivetin
user@host: docker create --name olivetin -p 1337:1337 -v /etc/OliveTin/:/config:ro docker.io/jamesread/olivetin
....

NOTE: The OliveTin container is built using fedora-minimal, which doesn't use customizations that some people may be familiar with from popular projects like LSIO, or debian-based containers. The two top misunderstandings are <<no-puid-pgid,PUID and PGID are ignored>>. Please see the instructions below if you're not familiar with changing users or timezones.

[#container-user]
== Container user

OliveTin does not need to be run as a root, and does not need any special capabilities. If you want to change the user that OliveTin runs as, use `--user` when creating the container. OliveTin ignores <<no-puid-pgid,PUID and PGID>>.

[#container-timezone]
== Container timezone

To change the <<timezone,changing the timezone requires a bound-mount>> from the host. Olivetin ignores the TZ variable as it is non-standard.

include::snippit_post_container.adoc[]
