[#install-helm]
= Kubernetes with Helm

Helm makes installing OliveTin on Kubernetes very easy, the official chart is hosted on Artifact Hub. 

https://artifacthub.io/packages/search?repo=olivetin[image:https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/olivetin[Artifact Hub]]

== Dependencies

* [X] A Kubernetes environment setup and running
* [X] Kubernetes client installed and authenticated
* [X] An ingress controller configure for web traffic
* [X] Helm installed and authenticated to the cluster

== Installation

[source,shell]
----
user@host: helm repo add olivetin https://olivetin.github.io/OliveTin-HelmChart/
user@host: helm install olivetin olivetin/olivetin
NAME: olivetin
LAST DEPLOYED: Tue Apr  1 23:19:09 2025
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
----

== Configure

After a minute or two, check the pod status;

[source,shell]
----
user@host: kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
olivetin-578b79766-4b8lg   1/1     Running   0          87s
----

Hopefully the pod is not crashlooping or anything like that. If it is, check the logs.

The helm chart should have created a basic ConfigMap for you;

[source,shell]
----
user@host: kubectl describe cm/olivetin-config
Name:         olivetin-config
Namespace:    default
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: olivetin
              meta.helm.sh/release-namespace: default

Data
====
config.yaml:
--
actions:
  - title: "Hello world!"
    shell: echo 'Hello World!'

----

You should edit this ConfigMap to match your needs for OliveTin. Remember to restart the OliveTin deployment if you want the config changes to be picked up more quickly; 

[source,shell]
----
user@host: kubectl rollout restart deploy/olivetin
deployment.apps/olivetin restarted
----

== Optional: Install kubernetes-client inside OliveTin container

The OliveTin container runs as a non-privileged user by default, so to install packages you need to become root. The quick and easy way to do this in Kubernetes without building your own image is to switch the SecurityContext to run OliveTin as a root;

.Find this...
[source,yaml]
----
      securityContext: {}
----

.Replace with...
[source,yaml]
----
      securityContext:
	    runAsUser: 0
----

You can then follow the instructions to xref::reference/containerInstallPackages.adoc[install extra packages in containers]. For example;

[source,bash]
----
user@host: kubectl exec -it deploy/olivetin -- /bin/bash
bash-5.2# microdnf install kubernetes-client
Updating and loading repositories:
Repositories loaded.
Package "kubernetes-client-1.29.14-2.fc40.x86_64" is already installed.

Nothing to do.
bash-5.2#
----

=== Allow OliveTin container to get pods;

Create the following cluster role;

[source,yaml]
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
----

Create a cluster role binding;

[source,shell]
----
user@host: kubectl create clusterrolebinding --clusterrole=pod-reader --serviceaccount myolivetinnamespace:default --namespace myolivetinnamespace read-pods-default
----

Add `kubectl` job to OliveTin config with `kubectl edit cm/olivetin-config`;

[source,yaml]
----
apiVersion: v1
data:
  config.yaml: |
    actions:
      - title: "Hello world!"
        shell: echo 'Hello World!'

      - title: "Get pods"
	    shell: kubectl get pods
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: olivetin
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  name: olivetin-config
  namespace: default
----

Don't forget to restart the OliveTin deployment as good measure, because Kubernetes can be slow to update configmaps.

include::partial$install/to_config.adoc[]

== Included templates

You can view the raw templates here: https://github.com/OliveTin/OliveTin-HelmChart/tree/main/templates

* Deployment
* ConfigMap
* Service
* Ingress (optional)

