[#actions]
== Actions

[#exec-on-demand]
=== Execute on demand

This is the default, meaning that the action shows up on a dashboard, and at the moment cannot be changed.

[#exec-cron]
=== Execute on schedule (cron)

OliveTin can execute actions on a schedule, and uses a cron format for configuration.

----
actions:
  - title: Say hello
    shell: echo "Hello!"
    execOnCron: 
      - "@hourly"

  - title: Say goodbye
    shell: echo "Say Goodbye"
    execOnCron:
      - "*/5 * * * *" # Every 5 minutes
----

This is a fantastic website: https://cron.help/

[#exec-startup]
=== Execute on startup

OliveTin can execute actions on a startup. 

----
actions:
  - title: Say hello
    shell: echo "Hello!"
    execOnStartup: true 
----

[#dnf-startup]
==== Example: Install additional commands into OliveTin

This functionality to execute actions on startup is a very easy way to install additional commands in OliveTin;

----
actions:
  - title: Install dnsmasq
    shell: microdnf install bind-utils
    execOnStartup: true
----

To learn more about how to install additional packages into the container, see <<container-dnf,installing extra container packages>>.

[#exec-file-created]
=== Execute on file created

You can execute an action when a file is created in a directory. The argument `filename` is pre-populated for you.

----
actions:
  - title: Print names of new files
    shell: echo {{ filename }}
    execOnCreatedInDir:
      - /home/user/Downloads/
----

[#exec-file-changed]
=== Execute on file changed

You can execute an action when a file is changed in a directory. The argument `filename` is pre-populated for you.

----
actions:
  - title: Print names of new files
    shell: echo {{ filename }}
    execOnFileChangedInDir:
      - /home/user/Downloads/
----


