[#actions]
== Actions 

[#action-container-control]
=== Containers - start/stop

:systemd: Easy
:container: Setup needed - see below
include::actionHeader.adoc[]

[#example-control-containers]
....
actions:
  - title: Stop Plex
    shell: docker stop plex

  - title: Start plex
    shell: docker start plex
....

==== Setup if running inside a container

You can control other containers, when running OliveTin inside a container
itself, however you need to do some extra setup when creating the OliveTin
container.

NOTE: If you want to control Docker from inside a Docker container, you will need to also create the container with `--privileged`. Podman does not have this requirement.

. Pass `/var/run/docker.sock` as a bind mount to the container when creating it, eg:
+
----
docker create --privileged -v /var/run/docker.sock:/var/run/docker.sock ...additional args here...
----
+
Or, using the `docker run` syntax;
+
----
docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock --name OliveTin jamesread/olivetin
----
+
. The official x86_64 docker container comes with the `docker` client pre-installed. If you are using `arm` or and `arm64` container, you will need to add Docker yourself.
+
<<container-dnf,How to install additional packages in the container>>
+
NOTE: The reason that the `arm` and `arm64` containers do not container docker, is that when these images are cross-compiled at build time, it takes FOREVER because we have to emulate arm. 

After you have passed the socket into the container (and optionally installed docker), you should be able to setup docker actions like it's shown in the example <<example-control-containers,above>>.


[#action-service]
=== Restart a systemd service

:systemd: Easy
:container: Not really possible to do.
include::actionHeader.adoc[]

....
actions:
  - title: Start httpd
    shell: systemctl start httpd

  - title: Stop httpd
    shell: systemctl stop httpd

  - title: Restart httpd
    shell: systemctl restart httpd
....

[#action-ping]
=== Ping an address

:systemd: Easy
:container: Easy
include::actionHeader.adoc[]
....
actions:
    # This sends 1 ping to google.com.
  - title: ping google.com
    shell: ping google.com -c 1
    icon: ping
    timeout: 3
....

include::action-ssh.adoc[]

[#powershell]
=== Powershell

:systemd: Easy
:container: Not possible
include::actionHeader.adoc[]

Powershell requires `pwsh` to execute commands.

....
actions:
  - title: Run Powershell Script:
    shell: pwsh C:/Scripts/MyScript.ps1
....



