[#examples]
== Action examples 

[#action-container-control]
=== Containers - start/stop

:systemd: Easy
:container: Setup needed - see below
include::actionHeader.adoc[]

[#example-control-containers]
....
actions:
  - title: Stop Plex
    shell: docker stop plex

  - title: Start plex
    shell: docker start plex
....

include::snippit_container_socket.adoc[]

[#action-service]
=== Restart a systemd service

:systemd: Easy
:container: Not really possible to do.
include::actionHeader.adoc[]

[source,yaml]
....
actions:
  - title: Start httpd
    shell: systemctl start httpd

  - title: Stop httpd
    shell: systemctl stop httpd

  - title: Restart httpd
    shell: systemctl restart httpd

  # https://docs.olivetin.app/action-ssh.html
  - title: Restart httpd on server 1
    shell: ssh root@server1 'service httpd restart'
....

[#action-ping]
=== Ping an address

:systemd: Easy
:container: Easy
include::actionHeader.adoc[]
....
actions:
    # This sends 1 ping to google.com.
  - title: ping google.com
    shell: ping google.com -c 1
    icon: ping
    timeout: 3
....

include::action-ssh.adoc[]

[#powershell]
=== Powershell

:systemd: Easy
:container: Not possible
include::actionHeader.adoc[]

Powershell requires `pwsh` to execute commands.

....
actions:
  - title: Run Powershell Script:
    shell: pwsh C:/Scripts/MyScript.ps1
....


[#ansible-playbook]
=== Ansible Playbooks

:systemd: Easy
:container: Install the `ansible` package in your <<container-dnf,OliveTin container>>.
include::actionHeader.adoc[]

Many users use OliveTin to easily execute Ansible playbooks, somtimes as a simple alternative to AWX.

.Run an Ansible Playbook
[source,yaml]
----
actions:
  - title: Run Ansible Playbook
    icon: "&#x1F1E6;"
    shell: ansible-playbook -i /etc/hosts /root/myRepo/myPlaybook.yaml
    timeout: 120
----

You probably want to set the <<timeout>> to more than the default 3 seconds.

