== Actions 

[#action-container-control]
=== Containers - start/stop

:systemd: Easy
:container: 1) Pass /var/run/docker.sock as a bind mount to the container when creating it. 2) Install docker command into the container.
include::actionHeader.adoc[]
....
actions:
  - title: Stop Plex
    shell: docker stop plex

  - title: Start plex
    shell: docker start plex
....

[#action-service]
=== Restart a systemd service

:systemd: Easy
:container: Not really possible to do.
include::actionHeader.adoc[]

....
actions:
  - title: Start httpd
    shell: systemctl start httpd

  - title: Stop httpd
    shell: systemctl stop httpd

  - title: Restart httpd
    shell: systemctl restart httpd
....

[#action-ping]
=== Ping an address

:systemd: Easy
:container: Easy
include::actionHeader.adoc[]
....
actions:
    # This sends 1 ping to google.com.
  - title: ping google.com
    shell: ping google.com -c 1
    icon: ping
    timeout: 3
....

[#action-ssh]
=== SSH into another machine and run a command

:systemd: Easy
:container: Needs some setting up - if you are using the default container image you will need to run the command `dnf install openssh-clients` first.
include::actionHeader.adoc[]

....
actions:
    # This will SSH into a server an run the command 'service httpd restart'
   - title: Restart httpd on Server 1
     shell: ssh server1 'service httpd restart'
     icon: ping
     timeout: 5
....

*Note about SSH keys*: You should make sure that the user that OliveTin is running as has access
to a SSH key. There are lots of good articles on the internet that explain how
to setup password-less login with a SSH key. This applies to container images
as well.


