[#actions]
== Actions 

[#action-container-control]
=== Containers - start/stop

:systemd: Easy
:container: Setup needed - see below
include::actionHeader.adoc[]
....
actions:
  - title: Stop Plex
    shell: docker stop plex

  - title: Start plex
    shell: docker start plex
....

==== Setup if running inside a container

You can control other containers, when running OliveTin inside a container
itself, however you need to do some extra setup when creating the OliveTin
container.

1) Pass `/var/run/docker.sock` as a bind mount to the container when creating it,
eg:

----
docker create -v /var/run/docker.sock:/var/run/docker.sock ...additional args here...
----

Or, using the `docker run` syntax;

----
docker run -v /var/run/docker.sock:/var/run/docker.sock --name OliveTin jamesread/olivetin
----

2) The official x86_64 docker container comes with the `docker` client pre-installed. If you are using `arm` or and `arm64` container, you will need to add Docker yourself.

----
docker exec -it olivetin dnf install -y docker
----

NOTE: The reason that the `arm` and `arm64` containers do not container docker, is that when these images are cross-compiled at build time, it takes FOREVER because we have to emulate arm. 

After that, you should be able to setup docker actions like it's shown in the example above.


[#action-service]
=== Restart a systemd service

:systemd: Easy
:container: Not really possible to do.
include::actionHeader.adoc[]

....
actions:
  - title: Start httpd
    shell: systemctl start httpd

  - title: Stop httpd
    shell: systemctl stop httpd

  - title: Restart httpd
    shell: systemctl restart httpd
....

[#action-ping]
=== Ping an address

:systemd: Easy
:container: Easy
include::actionHeader.adoc[]
....
actions:
    # This sends 1 ping to google.com.
  - title: ping google.com
    shell: ping google.com -c 1
    icon: ping
    timeout: 3
....

[#action-ssh]
=== SSH into another machine and run a command

:systemd: Easy
:container: Needs some setting up - if you are using the default container image you will need to run the command `dnf install openssh-clients` first.
include::actionHeader.adoc[]

....
actions:
    # This will SSH into a server an run the command 'service httpd restart'
   - title: Restart httpd on Server 1
     shell: ssh server1 'service httpd restart'
     icon: ping
     timeout: 5
....

*Note about SSH keys*: You should make sure that the user that OliveTin is running as has access
to a SSH key. There are lots of good articles on the internet that explain how
to setup password-less login with a SSH key. This applies to container images
as well.


