# This is for local testing only. OliveTin-antora builds prettydocs.olivetin.app.
---
site:
  title: OliveTin docs
  start_page: ROOT::index.adoc
  robots: allow
content:
  sources:
    - url: .
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: ./theme-supplemental/
    - path: ui.yml
      contents: |
        static_files:
        - CNAME
    - path: CNAME
      contents: |
        docs.olivetin.app
antora:
  extensions:
    - '@antora/lunr-extension'
