[#api]
== API 

=== OliveTin API Overview 
This section of the documentation is intended for developers, and those who want to hack around with OliveTin and extend it. This page provides a few pointers to get started. 

Short version: http://olivetinServer:1337/api for the REST API.

Longer version: The OliveTin API is formally defined using the Protobuf IDL, which generates gRPC stubs, as well as a REST Gateway. The REST gateway is used by the WebUI, and you can use it too by default. The gRPC API only listens on localhost default, but it can be set to listen publicly. See <<network-ports, the network ports documentation>> for a better description of how the APIs are exposed. 

==== Example API call: Start action via the API

===== Curl

----
user@host: curl -X POST "http://olivetin.webapps.teratan.lan/api/StartAction" -d '{"actionName": "Nuclear reactor shutdown"}'
----

===== Powershell

----
PS C:\Users\xcons> $json = '{"actionName": "Deploy attack Gnomes"}'
PS C:\Users\xcons> Invoke-RestMethod -Method "Post" -Uri "http://olivetinServer:1337/api/StartAction" -Body $json 
----

==== Example API calls - Get the dashboard buttons

GetDashboardComponents: http://olivetinServer:1337/api/GetDashboardComponents 

==== Links 

* link:http://docs.olivetin.app/api/[Swagger UI for OliveTin API]
* link:http://docs.olivetin.app/api/OliveTin.openapi.json[OpenAPI JSON]
* link:https://github.com/OliveTin/OliveTin/blob/main/OliveTin.proto[The OliveTin Protobuf file]. 

Please do talk to the developers on Discord if you'd like help using the API, or you're thinking about building something interesting using the API!
