[#api]
== API 

=== OliveTin API Overview 
This section of the documentation is intended for developers, and those who want to hack around with OliveTin and extend it. This page provides a few pointers to get started. 

**Short version**: http://olivetinServer:1337/api for the REST API. link:http://docs.olivetin.app/api/[Swagger] documents the API.

**Longer version**: The OliveTin API is formally defined using the Protobuf IDL, which generates gRPC stubs, as well as a REST Gateway. 

The REST API gateway is used by the WebUI, and you can use it too by default - it is exposed at "/api" by default.

The gRPC API only listens on localhost default, but it can be set to listen publicly. See <<network-ports, the network ports documentation>> for a better description of how the APIs are exposed. Most people do not need to use the gRPC API. The .proto file for the gRPC API is located at the root of the OliveTin Git repository; https://github.com/OliveTin/OliveTin/blob/main/OliveTin.proto[OliveTin.proto].

==== Links 

* link:http://docs.olivetin.app/api/[Swagger UI for OliveTin API]
* link:http://docs.olivetin.app/api/OliveTin.openapi.json[OpenAPI JSON Definition]
* link:https://github.com/OliveTin/OliveTin/blob/main/OliveTin.proto[The OliveTin Protobuf file]. 

Please do talk to the developers on Discord if you'd like help using the API, or you're thinking about building something interesting using the API!

[#api-start-action]
=== Starting Actions from the API

include::api_start_action_overview.adoc[]

[#api-request-idurl]
==== Request type: ID in the URL

Used by:

* `StartActionByGet`
* `StartActionByGetAndWait`

If you are trying to integrate OliveTin with your own scripts or processes, it's probably easiest to start actions by using an ID directly in the URL, <<api-eg-startIdUrl,see the example>>.

[#api-request-obj]
==== Request type: OliveTin request object

Used by:

* `StartAction`
* `StartActionAndWait`

If you need more control over the execution, then the only other option is to submit a `OliveTin reqjest object`, which is just a very simple JSON structure like this;

[source,json]
----
{
    "actionName": "Generate cryptocurrency",
    "arguments": [],
    "uuid": "my-tracking-id",
}
----

More detailed examples can be seen below.

==== Response type: Execution Tracking ID

Used by:

* `StartAction`
* `StartActionByGet`

==== Response type: LogEntry

Used by:

* `StartActionAndWait`
* `StartActionByGetAndWait`

[#api-eg-startIdUrl]
==== Example API call; Start an action by ID in the URL

.curl
----
user@host: curl http://olivetin.example.com/api/StartActionByGet/pingGithub
----

The corresponding config.yaml would look like this;

[source,yaml]
----
actions:
  - title: Ping GitHub.com
    id: pingGithub
    shell: ping github.com -c 1
----

IDs are used by these API calls, as you probably want the interface to display a human-readable title, whereas the API call doesn't want to have spaces or punctuation.

==== Example API call: Start an action using `StartAction`

[source,bash]
.curl
----
user@host: curl -X POST "http://olivetin.webapps.teratan.lan/api/StartAction" -d '{"actionName": "Nuclear reactor shutdown"}'
----

[source,powershell]
.Powershell
----
PS C:\Users\xcons> $json = '{"actionName": "Deploy attack Gnomes"}'
PS C:\Users\xcons> Invoke-RestMethod -Method "Post" -Uri "http://olivetinServer:1337/api/StartAction" -Body $json 
----

==== Example API call: Start an action using `StartAction` with arguments

[source,bash]
.curl
----
user:host: curl -X POST 'http://olivetin.example.com/api/StartAction' -d '{"actionName": "Ping host", "arguments": [{"name": "host", "value": "example.com"},{"name": "count", "value": "1"}]}'
----

=== Misc API calls

==== Example API call: Get the dashboard buttons ("components")

.curl
----
user@host: curl http://olivetinServer:1337/api/GetDashboardComponents 
----


