[#auth]
== Authentication & Authorization

See <<auth-concepts,concepts>> for a good overview of how this works in OliveTin. 

[#auth-concepts]
=== Concepts

OliveTin does not have any built-in code for doing **Authentication** (ie: entering a username and password), however it can do **Authorization** (ie: checking permissions of a user who logged in via another system, like single sign on).

A popular way of deploying OliveTin is by users accessing it via another system, like a <<reverse-proxies,reverse proxy>> (eg: Traefik) or a "homepage" app (eg: Organizr). Both of these are used to handle user authentication first, before users then access OliveTin. Permissions can then be applied inside OliveTin depending on who has logged in.

The flow generally goes like this; 

1. User browses to a website like Organizr and logs in, which sets a JWT Cookie for apps.example.com.
2. User browses to OliveTin.apps.example.com, and the cookie is sent to OliveTin.
3. OliveTin verifies the JWT token given the signing secret, and picks up on the `name` and `group` fields from the JWT claim.
4. OliveTin matches any relevant ACLs based on the claims.
5. If any ACLs are not matched, then the defaultPermissions are used.

[#trusted-header]
=== Trusted Header Authorization

This method is not yet well documented, sorry! Ask on Discord - we need more people to test this feature.

----
authHttpHeaderUsername: "X-Username"
authHttpHeaderUsergroup: "X-Usergroup"
----

NOTE: You *must* set `AuthHttpHeaderUsername` to some value, even if you only intend to use `AuthHttpHeaderUsergroup`, otherwise usergroups will be ignored.

[#jwt]
=== JWT Authorization

You need to know your JWT **Cookie Name** and **Hash Secret**. Whatever tool you are using to authenticate users will probably have instructions on how to find this.

* link:https://docs.organizr.app/features/server-authentication#validating-the-token[Organizr - Under "Validating the token"]

==== Adding JWT details to OliveTin config.yaml

Setup your config file so it has something like this;

----
# It's often useful to turn logging to DEBUG when trying to work out authentication problems
logLevel: "INFO"

authJwtCookieName: "Organizr_token_1234..."
authJwtSecret: "3l4jh23v_123!"
authJwtClaimUsername: "username"
authJwtClaimUsergroup: "usergroup"
----

Note that your `authJwtCookieName` and `authJwtSecret` will need to be set exactly as they appear in your Authentication software.

==== Usable claims

OliveTin currently can match Access Control Lists based on a **username** or **primary user group**. These must be called `name` and `group` respectively. You can see if these are being used properly turning on `DEBUG` logging and looking at the jwt claims.

==== Setup default permissions

OliveTin will assume that guests are able to View and Execute every action by default. When you are setting up authorization you probably want to limit this. You can do that by setting `defaultPermissions` like this;

----
logLevel: "INFO"

defaultPermissions:
    view: false
    exec: false
----

====  Setup OliveTin Access Control Lists 

Access Control Lists are a way to override the default permissions.

----
logLevel: "INFO"

defaultPermissions:
    view: false
    exec: false
    logs: true

accessControlLists:
    - name: Admins
      addToEveryAction: true
      matchUsergroups: 
      - Admins
      permissions:
        view: true
        exec: true
        logs: true

    - name: "Developers"
      matchUsergroups:
      - "developer"
      permissions:
        view: true
        exec: false
        logs: false

actions:
    - name: Only visible to admins
      shell: echo "I am a secret command only visible to admins"

    - name: Restart database
      shell: systemctl restart mariadb
      acls:
        - "developer"
----

In the example above, the `admins` ACL is automatically added to every action, because `addToEveryAction` is true. 

==== Customizing field names

You may need to customize the field names for your JWT authentication. 

----
authJwtClaimUsername: "username"
authJwtClaimUsergroup: "usergroup"
----

[#acls]
=== Access Control

include::snippit_earlydoc.adoc[]

OliveTin supports Access Control Lists.

You can have one default access control list, list this;

[source,yaml]
----
defaultPermissions:
  view: false
  exec: false
  logs: true

accessControlLists:
  - name: admins
    addToEveryAction: true
    permissions:
      view: true
      exec: true
      logs: true
----

Or you can specify access control lists per action:

You can have one default access control list, list this;

[source,yaml]
----
defaultPermissions:
  view: false
  exec: false

accessControlLists:
  - name: admins
    permissions:
      view: true
      exec: true

actions:
  - title: Shutdown Reactor
    acls:
      - admins
----

