[#config]
== Configuration

OliveTin is controlled by a `config.yaml` file. On startup, it looks for this
file in the following locations; 

1. The value specified by the `--configdir` argument, which defaults to the current working directory (`./`)
2. `/config/` - Mostly used for containers
3. `/etc/OliveTin/` - this is the recommended directory on Linux for your `config.yaml`. 

The most simple `config.yaml` would be something like this;

.The most simple `config.yaml` file.
[source,yaml]
----
actions:
  - title: "Hello world!"
    shell: echo 'Hello World!'
----

It doens't really get more complicated than that. You can of course add more actions, and customize more, but the syntax otherwise extremely simple. 

For building up from here, look at the following resources; 

* See the <<actions,actions>> documentation for extra examples of what OliveTin could be configured to do.

* See the <<action-customisation,action cutomisation>> documentation to customize how those actions work.

