[#container-dnf]
=== Installing extra container packages

The official OliveTin container image is based on Fedora Linux. Fedora has shown to offer a great mix of stability and support over two decades. The base container image for OliveTin is relatively lightweight, with not many tools installed by default. This keeps the download size small, but you may want to add additional packages.

==== Quickstart - using DNF to install additional packages

You can of course create your own container image, but this is probably a lot of work for new users, or people who just want a few extra packages/commands. Instead of creating a whole new container image, you can simply run `dnf` (the Fodora package manager) to install more commands.

Start the OliveTin container using one of the methods shown in the <<installation,installation instructions>>.

Then, on the same host that is running the container, spawn a root shell inside the OliveTin container, like this;

----
user@host: docker exec -it olivetin -u root /bin/bash
[root@019d08ef95bd /]#
----

The important thing here is passing `-u root`. By default, OliveTin does not run as root.

Once you have a root shell in OliveTin, you can use the Fedora package manager - `dnf` to install things that you might need. If you are used to Debian's `apt-get` tool, it works in a very similar way;

----
[root@019d08ef95bd /]# dnf install -y nc
----

Note that if you upgrade the OliveTin container image, you will need to reinstall these packages.

Once you have finished installing these packages, just exit the root shell using `exit`. You don't need to restart the container - and OliveTin does not need to run as root to use most commands.

==== Installing packages non-interactively

If your Docker container is rebuilt, you'll need to perform these steps again. To make this easier, here's an example of a script that installs Docker Compose after your container is rebuilt:

----
#!/bin/bash

docker="/usr/bin/docker"
echo="/usr/bin/echo"
grep="/usr/bin/grep"

# Install Docker Compose in olivetin
container_name="olivetin"
if ${docker} ps --format '{{.Names}}' | ${grep} -Eq "^${container_name}\$"; then
  # ${docker} exec -i "${container_name}" /bin/bash -c "/bin/microdnf install -y yum-utils && /bin/dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo && /bin/dnf install -y docker-compose-plugin"
  ${docker} exec -i "${container_name}" /bin/bash -c "/bin/mkdir -p /usr/local/lib/docker/cli-plugins && /bin/curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose && /bin/chmod +x /usr/local/lib/docker/cli-plugins/docker-compose"
else
  ${echo} "${container_name}" not running
fi

exit
----

Just change the `container_name` variable to whatever you've named your Docker container for OliveTin.

==== See also

* link:https://hub.docker.com/r/jamesread/olivetin[OliveTin container on Docker Hub]
* <<install-container,Installing using a container>>
* <<install-compose,Installing using docker compose>>
* <<install-helm,Installing on Kubernetes with Helm>>
* <<install-k8s,Installing on Kubernetes (manually)>>
