[#donations-and-sponsorship]
=== Donations & Sponsorship

Sometimes I (James Read) get asked if people can donate money, or sponsor me for OliveTin. If you are reading this page, maybe you are thinking the same.

**I do not accept donations or sponsorship** for OliveTin, but I want to **thank you very much indeed** for thinking about the potential.

I have a job that pays me, where I don't write code as part of my day job (very often) - I enjoy coding as a hobby in my spare time. If I get money for that, it somehow takes the pleasure or fun out of it, or makes it feel like a job. There are concerns that I might "prefer" to work on a feature if I am sponsored, or even feel compelled that I have to work on something because someone gave me money. I don't want OliveTin development to go that way. There are also little other considerations, like being paid on the side out of my job then affects my job, and tax, and so on and so on.

Other ways that you can show your appreciation for OliveTin, that actually mean a lot more than money;

. Share your use case online, on Reddit, Twitter, or whatever - show people what you are using OliveTin for. There is also #screenshot-showcase in the OliveTin Discord community.
. If you still want to show thanks, jump on Discord and just say it, or contact me via one of the methods found at http://jread.com .
. Lastly, if you have a homelab, or spare server capacity where I can have a virtual machine with root access, then having more VMs to test OliveTin on is always very welcome indeed. I have a lot of sever capacity already though personally, so I'm probably just being greedy for CPU and RAM :-)
