==== Post installation (container)

You will need to write a basic configuration file before OliveTin will startup.

Create a basic config file at somewhere like `/docker/OliveTin/config.yaml` - the exact path depends on what directory you specified in the bind mount container creation. Note that OliveTin containers expect the config to be in `/config/` inside the container, but it doesn't really matter where this directory is mounted from on the host. The file contents should look something like this;

.The most simple `config.yaml` file.
[source,yaml]
----
actions:
  - title: "Hello world!"
    shell: echo 'Hello World!'
----

Now that you have a configuration file, and the OliveTin container created, you should be able to start the container like normal.

If you are running a firewall on your server, like firewalld, you will need to
open port 1337;

[source, shell]
----
user@host: firewall-cmd --add-port 1337/tcp --permanent
user@host: firewall-cmd --reload
----

include::install_to_config.adoc[]

==== Troubleshooting podman/docker installations

If you are having problems in starting OliveTin, or OliveTin is crashing on startup, then check the logs like this;

----
user@host: docker logs OliveTin
----

If you cannot understand the logs, or otherwise need help, see the <<support>>.
