[#install-linuxpackage]
=== Recommended: Installation with a Linux package, using systemd

Running OliveTin as a systemd service on a Linux machine means it can use any program installed on your machine (you don't have to add programs to a container). This is generally easier to use than a container, but containers can work just fine too with a bit more effort.

==== Choosing the right Linux package

There are .deb, .rpm, and similar packages published for OliveTin on each
release page. Pick a package most relevant to the Linux distribution you are
using from the link:https://github.com/jamesread/OliveTin/releases[downloads page].

If you're not sure which package to use, see <<choose-package,which download do I need?>>

You can install these packages with your Linux package manager (eg, 
`dpkg -i OliveTin...deb` or `rpm -U OliveTin...rpm`). 

include::install_post_systemd.adoc[]

[#install-targz]
=== Installation from a .tar.gz manually, using systemd

This is an option for an advanced setup, for users who cannot user the .deb or .rpm packages.

==== Manual setup (.tar.gz)

A .tar.gz file is provided for people who are using other Linux distributions or want to set things up manually. 

1. Copy the `OliveTin` binary to `/usr/local/bin/OliveTin`
2. Copy the `webui` directory contents to `/var/www/olivetin/` (eg, `/var/www/olivetin/index.html`)
3. Copy the `OliveTin.service` file to `/etc/systemd/system/`
4. Create a `config.yaml` in `/etc/OliveTin` using the example provided above to get you started.

include::install_post_systemd.adoc[]


