[#reverse-proxies]
== Reverse Proxies

This section of the documentation has a few examples of reverse proxy configurations for popular reverse proxy servers.

Configuring a reverse proxy server for OliveTin is entirely optional. If you don't want to use a reverse proxy, you can skip this section.

[#proxy-guide]
=== Reverse Proxy general guide

It's common to put OliveTin behind a reverse proxy, for authentication, customizing the OliveTin address/path, or for a variety of other reasons. 

==== DNS name vs Path based proxies

DNS Name based virtual hosts (eg: olivetin.example.com ) are easier to setup and configure than path based virtual hosts (eg: www.example.com/utils/OliveTin), because path based virtual hosts need to take care mangle OliveTin paths without breaking things.

* If using a path based reverse proxies, you may need to set `externalRestAddress` manually to something like; `http://example.com/utils/OliveTin` in the OliveTin config.yaml.
* If using DNS Name based reverse proxies, then you should not need to change anything in config.yaml

===== Which port?

If you look at OliveTin startup logs, you will see OliveTin starting services on several ports. For most users, even under reverse proxy configurations, just proxying port 1337 should be all that is needed. To better understand why OliveTin uses several internal ports by default, see <<network-ports,network-ports>>.

==== Handling websockets

OliveTin versions after 2023-08 use websockets instead of polling for updates. Taking care to re-pass the `Connection: Upgrade` and `Upgrade: websocket` headers for the `/websocket` path. 

===== General checklist

* `olivetin.example.com/*` is all just HTTP traffic (port 1337)
** `olivetin.example.com/` should show the standard webui (port 1337)
** `olivetin.example.com/webUiSettings.json` should return a JSON file generated by OliveTin that sets up the web interface. (port 1337)
** `olivetin.example.com/api` should how the REST based API. (port 1337)
* `olivetin.example.com/websocket` should be a websocket connection upgrade.

[#apache-path]
[#apache-dns]
=== Apache HTTPD - DNS based

This is a an example of how to setup a DNS name based Apache HTTPD proxy for OliveTin. It assumes OliveTin is running on localhost, port 1337. 

----
<VirtualHost *:80>
ServerName olivetin.example.com
ProxyPass /utilities/OliveTin/ http://localhost:1337/
ProxyPassReverse /utilities/OliveTin/ http://localhost:1337/
</VirtualHost>
----

Note, you virtual host should *not* include a DocumentRoot directive - httpd is just proxying OliveTin, not serving it's actual pages. 

[#haproxy-dns]
=== Haproxy - DNS based

This is a straightforward example of how to setup a DNS name based HAProxy setup for OliveTin.

----
frontend cleartext_frontend
    mode http
    bind 0.0.0.0:80

    option httplog

    use_backend be_olivetin if { hdr(Host) -i olivetin.example.com }

backend be_olivetin
    server olivetinServer 192.168.0.1:1337 check

----

[#traefik-docker-compose]
=== Traefik + Docker Compose

The following example is known to work well with Traefik and docker-compose.

----
version: "3.8"
services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - /docker/olivetin:/config # replace host path or volume as needed
    ports:
      - "1337:1337"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.olivetin.entrypoints=web"
      - "traefik.http.routers.olivetin.rule=Host(`olivetin.example.com`)"

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
----

[#nginx-dns]
=== Nginx - DNS based

This is an example of DNS based proxying with Nginx.

./etc/nginx/cond.d/OliveTin.conf
----
include::etc/reverse_proxy_nginx_dns.conf[]
----


[#nginx-path]
=== Nginx - Path based

.nginx.conf
----
....
        location /OliveTin/ {
                proxy_pass http://localhost:1337/;
                proxy_redirect http://localhost:1337/ http://localhost/OliveTin/;
        }
....
----

include::fragment-external-rest.adoc[]

[#caddy-path]
=== Caddy - Path based

.Caddyfile
----
....
	handle {$GLOBAL_PORTAL_PATH}/olivetin* {
			redir {$GLOBAL_PORTAL_PATH}/olivetin {$GLOBAL_PORTAL_PATH}/olivetin/
			uri strip_prefix {$GLOBAL_PORTAL_PATH}/olivetin       
			basicauth {              
					{$GLOBAL_USER} HASH
			}     
			reverse_proxy * localhost:1337
	}
....
----

include::fragment-external-rest.adoc[]


