[#reverse-proxies]
== Reverse Proxies

This section of the documentation has a few examples of reverse proxy configurations for popular reverse proxy servers.

Configuring a reverse proxy server for OliveTin is entirely optional. If you don't want to use a reverse proxy, you can skip this section.

[#proxy-guide]
=== Reverse Proxy general guide

It's common to put OliveTin behind a reverse proxy, for authentication, customizing the OliveTin address/path, or for a variety of other reasons. 

For most users, even under reverse proxy configurations, just proxying port 1337 should be all that is needed. For a more detailed understanding of the different ports that OliveTin uses, and why, see the <<network-ports,network ports>> page.

* DNS Name based virtual hosts ( olivetin.example.com ) as easier to setup and configure than path based virtual hosts ( www.example.com/utils/OliveTin), because path based virtual hosts need to take care not to mangle OliveTin paths.
* If using a path based virtual host, you may need to set `externalRestAddress` manually to something like; `http://example.com/utils/OliveTin` in the OliveTin config.yaml.
* DNS Name based reverse proxies should work like this; 
** `olivetin.example.com` should how the standard webui (port 1337)
** `olivetin.example.com/webUiSettings.json` should return a JSON file generated by OliveTin that sets up the web interface. (port 1337)
** `olivetin.example.com/api` should how the REST based API. (port 1337)

[#apache-path]
=== Apache HTTPD - DNS based

This is a an example of how to setup a DNS name based Apache HTTPD proxy for OliveTin. It assumes OliveTin is running on localhost, port 1337. 

----
<VirtualHost *:80>
ServerName olivetin.example.com
ProxyPass /utilities/OliveTin/ http://localhost:1337/
ProxyPassReverse /utilities/OliveTin/ http://localhost:1337/
</VirtualHost>
----

Note, you virtual host should *not* include a DocumentRoot directive - httpd is just proxying OliveTin, not serving it's actual pages. 

[#haproxy-dns]
=== Haproxy - DNS based

This is a straightforward example of how to setup a DNS name based HAProxy setup for OliveTin.

----
frontend cleartext_frontend
    mode http
    bind 0.0.0.0:80

    option httplog

    use_backend be_olivetin if { hdr(Host) -i olivetin.example.com }

backend be_olivetin
    server olivetinServer 192.168.0.1:1337 check

----

[#traefik-docker-compose]
=== Traefik + Docker Compose

Please see the <<docker-compose-traefik,traefik section, in the docker compose installation instructions>> for details.

[#nginx-path]
=== Nginx - Path based

.nginx.conf
----
....
        location /OliveTin/ {
                proxy_pass http://localhost:1337/;
                proxy_redirect http://localhost:1337/ http://localhost/OliveTin/;
        }
....
----

include::fragment-external-rest.adoc[]

[#caddy-path]
=== Caddy - Path based

.Caddyfile
----
....
	handle {$GLOBAL_PORTAL_PATH}/olivetin* {
			redir {$GLOBAL_PORTAL_PATH}/olivetin {$GLOBAL_PORTAL_PATH}/olivetin/
			uri strip_prefix {$GLOBAL_PORTAL_PATH}/olivetin       
			basicauth {              
					{$GLOBAL_USER} HASH
			}     
			reverse_proxy * localhost:1337
	}
....
----

include::fragment-external-rest.adoc[]


