[#cloudflare-access-tunnels]
=== Cloudflare Access & Tunnels
:title: blat

include::snippit_earlydoc.adoc[]

Several uses use Cloudflare Access & Tunnels to grant access to OliveTin. There is no special configuration needed for OliveTin to work in this way, simply setup your Cloudflare tunnel to connect to OliveTin on port 1337.

If you are using Cloudflare Access, and want to use the username given by Cloudflare in OliveTin ACLs, then you can use the Cloudflare cookie like this;

[source,yaml]
.`config.yaml`
----
authHttpHeaderUsername: "Cf-Access-Authenticated-User-Email"

defaultPermissions:
    view: false
    exec: false

accessControlLists:
    - name: Admins
      addToEveryAction: true
      matchUsernames:
        - contact@jread.com
      permissions:
        view: true
        exec: true

actions:
  - title: test apprise
    shell: date
    shellAfterCompleted: "apprise -c /config/apprise.yml -t 'notification: test' -b 'date is {{ stdout }}'"
----

NOTE: OliveTin does support JWT cookies that Cloudflare uses, which is arguably more secure. It's just that nobody in the Discord has worked out how to get the keys needed from Cloudflare to decrypt this cookie yet! See the <<jwt>> documentation for some starter points. If you figure this out, it would be most welcome to share your solution with the community.

