[#themes-dev]
=== Themes (for theme developers)

include::../../snippit_earlydoc.adoc[]

==== Step by step theme guide

* Go to https://github.com/OliveTin/theme-template and use this template repository to create your new theme repository on GitHub. 
* Install OliveTin somewhere, and clone your new repository using `git clone` into your themes directory.
* Set `themeName: <your-folder>` in your OliveTin config.yaml and restart OliveTin.

Write beautiful CSS to create your theme as you like it, commit your changes to git.

Note that OliveTin will load `/theme.css` depending on `themeName:` in your config file. Images and any other assets will be served at `/custom-webui/themes/mytheme/`.

==== How to list your theme on the OliveTin themes page

The OliveTin themes page is here; https://olivetin.app/themes

When you are done with your theme, fork https://github.com/OliveTin/themes on GitHub and create a new page under the "content" directory for your new theme. Commit that to GitHub and then raise a pull request.

If you meed more help, please jump on our discord server! 


