actions:
  - title: WakeOnLan Server1
    shell: awake A8:5E:45:E4:FF:2A
    icon: ping

  - title: Install awake on startup
    shell: microdnf install -y awake
    hidden: true
    execOnStartup: true
    timeout: 120
