[#themes]
=== Themes (for users)

You can look for themes on the link:http://www.olivetin.app/themes/[OliveTin Theme Site].

==== The custom-webui directory

When OliveTin starts up, it will try to create a directory called `custom-webui/themes/` in your config directory. This directory is where you can put your own custom themes.

OliveTin will then serve this theme directory at `http://yourserver:1337/custom-webui/themes/`, this means that all theme content should go into `/custom-webui/themes/mytheme/`.

Install Themes into your `custom-webui/themes/` directory, which should be in your config directory. If this directory does not exist, you can create it.

[source,yaml]
----
├── config.yaml
├── custom-webui
│   └── themes
│       └── custom-icons
│           ├── icon.png
│           └── theme.css
├── entities
│   ├── containers.json
│   ├── heating.yaml
│   ├── servers2.yml
│   ├── servers.yaml
│   └── systemd_units.json
└── installation-id.txt
----

==== Create your own theme (without any intention of publishing it)

Create a sub-directory under your theme directory (eg `custom-webui/themes/mytheme`);

Set your theme in your config

[source,yaml]
.`config.yaml`
----
themeName: mytheme
----

Add your css into `custom-webui/themes/mytheme/theme.css`.

Your theme css will be loaded "on top" of the existing stylesheet.

To test it is working, set your theme CSS to something ridiculous like;

----
body {
    background-color: red !important;
}
----

Profit.

Check out <<themes-dev>> for more information on how to develop themes.

